# Generated by Django 3.0.5 on 2020-08-28 11:00

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('main_title', models.CharField(max_length=256, verbose_name='Title')),
                ('background_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Background color')),
                ('main_content', wagtail.core.fields.StreamField([('guide_block', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True, verbose_name='Maps')),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Background image')),
            ],
            options={
                'verbose_name': 'Guide local page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GuideMainPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('main_title', models.CharField(max_length=256, verbose_name='Title')),
                ('color_one', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Color from')),
                ('color_two', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Color to')),
                ('guide_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Color for guides')),
                ('guide_content', wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StreamBlock([]))], blank=True, null=True, verbose_name='Guides')),
                ('map_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Color for maps')),
                ('map_content', wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StreamBlock([]))], blank=True, null=True, verbose_name='Maps')),
                ('guide_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image for guides')),
                ('map_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image for maps')),
            ],
            options={
                'verbose_name': 'Guide main page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
