# Generated by Django 3.0.5 on 2020-08-30 13:37

import colorfield.fields
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidepage',
            name='background_color',
        ),
        migrations.AddField(
            model_name='guidepage',
            name='color_one',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Color from'),
        ),
        migrations.AddField(
            model_name='guidepage',
            name='color_two',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Color to'),
        ),
        migrations.AlterField(
            model_name='guidemainpage',
            name='guide_content',
            field=wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StreamBlock([('link', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True, verbose_name='Guides'),
        ),
        migrations.AlterField(
            model_name='guidemainpage',
            name='map_content',
            field=wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StreamBlock([('link', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True, verbose_name='Maps'),
        ),
        migrations.AlterField(
            model_name='guidepage',
            name='main_content',
            field=wagtail.core.fields.StreamField([('guide_block', wagtail.core.blocks.StreamBlock([('title', wagtail.core.blocks.CharBlock(verbose_name='Title')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('file', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True, verbose_name='Maps'),
        ),
    ]
