# Generated by Django 3.0.5 on 2020-05-02 18:26

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('standart_link', models.CharField(max_length=255)),
                ('slider_type', models.CharField(choices=[('standart', 'Стандарт'), ('calendar', 'Календарь')], default='black', max_length=250, verbose_name='Тип слайда')),
                ('tag_link_one', models.CharField(max_length=255)),
                ('tag_link_two', models.CharField(max_length=255)),
                ('tag_link_three', models.CharField(max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Изображение слайдера',
                'verbose_name_plural': 'Изображения слайдера',
            },
        ),
    ]
