# Generated by Django 3.0.5 on 2020-05-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dop_slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='title_one',
            field=models.CharField(blank=True, max_length=250, verbose_name='подзаголовок один'),
        ),
    ]
