# Generated by Django 3.0.5 on 2020-05-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dop_slider', '0002_sliders_title_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliders',
            name='title_one',
        ),
    ]
