# Generated by Django 3.0.5 on 2020-05-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dop_slider', '0003_remove_sliders_title_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='title_one',
            field=models.CharField(blank=True, max_length=250, verbose_name='подзаголовок один'),
        ),
        migrations.AddField(
            model_name='sliders',
            name='title_three',
            field=models.CharField(blank=True, max_length=250, verbose_name='подзаголовок три'),
        ),
        migrations.AddField(
            model_name='sliders',
            name='title_two',
            field=models.CharField(blank=True, max_length=250, verbose_name='подзаголовок два'),
        ),
    ]
