# Generated by Django 3.0.5 on 2020-05-02 18:40

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dop_slider', '0005_auto_20200502_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliders',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='standart_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, verbose_name='подзаголовок'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='tag_link_one',
            field=models.CharField(max_length=255, verbose_name='ссылка 1'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='tag_link_three',
            field=models.CharField(max_length=255, verbose_name='ссылка 3'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='tag_link_two',
            field=models.CharField(max_length=255, verbose_name='ссылка 2'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='title_one',
            field=models.CharField(blank=True, max_length=250, verbose_name='подзаголовок 1'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='title_three',
            field=models.CharField(blank=True, max_length=250, verbose_name='подзаголовок 3'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='title_two',
            field=models.CharField(blank=True, max_length=250, verbose_name='подзаголовок 2'),
        ),
    ]
