# Generated by Django 3.0.5 on 2020-05-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dop_slider', '0008_sliders_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliders',
            name='tag_link_one',
            field=models.CharField(blank=True, max_length=255, verbose_name='ссылка 1'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='tag_link_three',
            field=models.CharField(blank=True, max_length=255, verbose_name='ссылка 3'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='tag_link_two',
            field=models.CharField(blank=True, max_length=255, verbose_name='ссылка 2'),
        ),
    ]
