# Generated by Django 3.0.5 on 2020-05-10 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_mediakit_mediakit'),
        ('dop_slider', '0009_auto_20200503_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='collect',
            field=models.CharField(blank=True, max_length=255, verbose_name='название подборки'),
        ),
        migrations.AddField(
            model_name='sliders',
            name='collect_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sliders_tag', to='blog.Tag', verbose_name='Tag подборки'),
        ),
    ]
