# Generated by Django 3.0.5 on 2020-05-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dop_slider', '0010_auto_20200510_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidersEN',
            fields=[
                ('sliders_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dop_slider.Sliders')),
            ],
            bases=('dop_slider.sliders',),
        ),
        migrations.AddField(
            model_name='sliders',
            name='locale',
            field=models.CharField(choices=[('ru', 'ru'), ('en', 'en')], default='ru', max_length=250, verbose_name='Language'),
        ),
    ]
