# Generated by Django 3.0.5 on 2020-05-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dop_slider', '0011_auto_20200516_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliders',
            name='collect_tag',
        ),
    ]
