# Generated by Django 3.0.5 on 2020-05-16 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_auto_20200516_1641'),
        ('dop_slider', '0012_remove_sliders_collect_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='collect_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sliders_tag', to='blog.Tags', verbose_name='Tag подборки'),
        ),
    ]
