# Generated by Django 3.0.5 on 2020-05-24 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('dop_slider', '0013_sliders_collect_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='calendar_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
