# Generated by Django 3.0.5 on 2020-06-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dop_slider', '0016_auto_20200601_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliders',
            options={'ordering': ['-ontop', 'order_num', 'draft', '-id'], 'verbose_name': 'Изображение слайдера', 'verbose_name_plural': 'Изображения слайдера'},
        ),
        migrations.AddField(
            model_name='sliders',
            name='draft',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='черновик'),
        ),
        migrations.AddField(
            model_name='sliders',
            name='ontop',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='в начало'),
        ),
        migrations.AddField(
            model_name='sliders',
            name='order_num',
            field=models.IntegerField(blank=True, default=999, verbose_name='Порядок'),
        ),
    ]
