# Generated by Django 3.0.5 on 2020-05-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpreviewpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coloredtag',
            name='color',
        ),
    ]
