# Generated by Django 3.0.5 on 2020-05-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_addtoproject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addtoproject',
            options={'verbose_name_plural': 'Присоединиться к проекту'},
        ),
        migrations.AddField(
            model_name='addtoproject',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
