# Generated by Django 3.0.5 on 2020-05-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200510_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediakit',
            name='mediakit',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='mediakit'),
        ),
    ]
