# Generated by Django 3.0.5 on 2020-05-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_mediakit_mediakit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='card_sub_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Подголовок карточки'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='card_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок карточки'),
        ),
    ]
