# Generated by Django 3.0.5 on 2020-04-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpage_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='page_type',
            field=models.CharField(choices=[('standart', 'Стандарт'), ('fullimage', 'Заливка картинкой'), ('video', 'Заливка видео')], default='standart', max_length=250),
        ),
    ]
