# Generated by Django 3.0.5 on 2020-04-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogpage_page_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpagegalleryimage',
            options={'verbose_name': 'Галлерея изображений', 'verbose_name_plural': 'Галлерея изображений'},
        ),
    ]
