# Generated by Django 3.0.5 on 2020-04-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200421_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='page_type_hover',
            field=models.CharField(choices=[('standart', 'Стандарт'), ('fullimage', 'Заливка картинкой'), ('video', 'Заливка анимации')], default='standart', max_length=250),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='page_type',
            field=models.CharField(choices=[('standart', 'Стандарт'), ('fullimage', 'Заливка картинкой'), ('video', 'Заливка анимации')], default='standart', max_length=250),
        ),
    ]
