# Generated by Django 3.0.5 on 2020-04-22 12:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0012_auto_20200422_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'категории'},
        ),
        migrations.AddField(
            model_name='blogpage',
            name='animate_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Анимированное изображение'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(max_length=250, verbose_name='Вступление'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='page_type',
            field=models.CharField(choices=[('standart', 'Стандарт'), ('fullimage', 'Заливка картинкой'), ('video', 'Заливка анимации')], default='standart', max_length=250, verbose_name='Тип карточки'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='page_type_hover',
            field=models.CharField(choices=[('standart', 'Стандарт'), ('fullimage', 'Заливка картинкой'), ('video', 'Заливка анимации')], default='standart', max_length=250, verbose_name='Тип карточки при наведении'),
        ),
    ]
