# Generated by Django 3.0.5 on 2020-04-22 13:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200422_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpagetag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='blogpagetag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
