# Generated by Django 3.0.5 on 2020-04-22 14:21

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blogpagetag_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='animate_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.BlogCategory', verbose_name='Категории'),
        ),
    ]
