# Generated by Django 3.0.5 on 2020-05-11 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_formfield_formpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='custom_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.FormField'),
        ),
    ]
