# Generated by Django 3.0.5 on 2020-04-22 16:05

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200422_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpagetag',
            options={},
        ),
        migrations.RemoveField(
            model_name='blogpagetag',
            name='color',
        ),
        migrations.RemoveField(
            model_name='blogpagetag',
            name='order',
        ),
        migrations.CreateModel(
            name='ColoredTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('order', models.CharField(blank=True, max_length=250, null=True, verbose_name='Уровень')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_item', to='blog.BlogPageTag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
