# Generated by Django 3.0.5 on 2020-05-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blogindexpage_custom_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='custom_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.FormPage'),
        ),
    ]
