# Generated by Django 3.0.5 on 2020-04-22 16:39

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0021_auto_20200422_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coloredtag',
            name='tag',
        ),
        migrations.AddField(
            model_name='coloredtag',
            name='tag',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
