# Generated by Django 3.0.5 on 2020-04-22 16:41

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0022_auto_20200422_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloredtag',
            name='tag',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='tagged_items', through='blog.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
