# Generated by Django 3.0.5 on 2020-04-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200422_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='page_color',
            field=models.CharField(choices=[('white', 'Белый'), ('black', 'Черный')], default='black', max_length=250, verbose_name='Цвет заголовков карточки'),
        ),
    ]
