# Generated by Django 3.0.5 on 2020-04-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_blogpage_page_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='page_type',
            field=models.CharField(choices=[('standart', 'Стандарт'), ('fullimage', 'Заливка картинкой'), ('video', 'Заливка анимации'), ('rekcard', 'Рекламный блок')], default='standart', max_length=250, verbose_name='Тип карточки'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='page_type_hover',
            field=models.CharField(choices=[('standart', 'Стандарт'), ('fullimage', 'Заливка картинкой'), ('video', 'Заливка анимации'), ('rekcard', 'Рекламный блок')], default='standart', max_length=250, verbose_name='Тип карточки при наведении'),
        ),
    ]
