# Generated by Django 3.0.5 on 2020-04-26 09:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20200426_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='content_body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('video', wagtail.embeds.blocks.EmbedBlock()), ('text', wagtail.core.blocks.RichTextBlock(blank=True, features=['h2', 'h3', 'bold', 'italic', 'link'])), ('hr', wagtail.core.blocks.RichTextBlock(blank=True, features=['hr']))], blank=True, null=True, verbose_name='Статья'),
        ),
    ]
