# Generated by Django 3.0.5 on 2020-04-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_coloredtag_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloredtag',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название'),
        ),
    ]
