# Generated by Django 3.0.5 on 2020-05-14 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20200514_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='sub_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_id', related_query_name='tag_id', to='blog.ColoredTag', verbose_name='Дополнительный тег'),
        ),
    ]
