# Generated by Django 3.0.5 on 2020-04-27 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_coloredtag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloredtag',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.ColoredTag'),
        ),
    ]
