# Generated by Django 3.0.5 on 2020-04-27 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20200427_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloredtag',
            name='name',
            field=models.CharField(default='Введите название', max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='coloredtag',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ColoredTag'),
        ),
    ]
