# Generated by Django 3.0.5 on 2020-05-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20200514_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='sub_tag',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent_id_id__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.ColoredTag', verbose_name='Дополнительный тег'),
        ),
    ]
