# Generated by Django 3.0.5 on 2020-05-15 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20200515_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageEN',
            fields=[
                ('blogpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BlogPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.blogpage',),
        ),
    ]
