# Generated by Django 3.0.5 on 2020-04-29 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0038_auto_20200429_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedpage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Основное изображение'),
        ),
    ]
