# Generated by Django 3.0.5 on 2020-05-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_blogpageen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'Главная странице карточек (не используйте и не меняйте)'},
        ),
        migrations.AlterModelOptions(
            name='blogindexpageen',
            options={'verbose_name': "Main cards page in English (don't use or modify)"},
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'ordering': ('date',), 'verbose_name': 'Статья на Русском'},
        ),
        migrations.AlterModelOptions(
            name='blogpageen',
            options={'verbose_name': 'Article in English'},
        ),
        migrations.AlterModelOptions(
            name='blogpreviewpage',
            options={'verbose_name': 'Старинца превью на русском'},
        ),
        migrations.AlterModelOptions(
            name='blogtagindexpage',
            options={'verbose_name': 'Старница тегов (не используйте и не меняйте)'},
        ),
        migrations.AlterModelOptions(
            name='formfield',
            options={'verbose_name': "Form field (don't use or modify)"},
        ),
        migrations.AlterModelOptions(
            name='formpage',
            options={'verbose_name': "Form page (don't use or modify)"},
        ),
        migrations.AlterModelOptions(
            name='searchpage',
            options={'verbose_name': "Search page (don't use or modify)"},
        ),
        migrations.AlterModelOptions(
            name='typedpage',
            options={'verbose_name': "Typed page (don't use or modify)"},
        ),
    ]
