# Generated by Django 3.0.5 on 2020-04-29 10:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0039_typedpage_main_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpagegalleryimage',
            options={'verbose_name': 'Галерея изображений', 'verbose_name_plural': 'Галерея изображений'},
        ),
        migrations.CreateModel(
            name='TypedPageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
                ('main_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.Tag', verbose_name='Основной тег')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='typed_gallery_images', to='blog.TypedPage')),
            ],
            options={
                'verbose_name': 'Галерея партнеров',
                'verbose_name_plural': 'Галерея партнеров',
            },
        ),
    ]
