# Generated by Django 3.0.5 on 2020-04-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20200429_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='typedpagegalleryimage',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнера'},
        ),
        migrations.AddField(
            model_name='typedpagegalleryimage',
            name='link',
            field=models.CharField(blank=True, max_length=250, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='typedpagegalleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=250, verbose_name='подзаголовок'),
        ),
    ]
