# Generated by Django 3.0.5 on 2020-05-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20200516_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddToProject',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='icon',
        ),
        migrations.DeleteModel(
            name='MediaKit',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='tags',
        ),
        migrations.AlterField(
            model_name='typedpagegalleryimage',
            name='main_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.Tags', verbose_name='Основной тег'),
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
