# Generated by Django 3.0.5 on 2020-05-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_auto_20200516_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
