# Generated by Django 3.0.5 on 2020-05-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0045_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема письма')),
            ],
            options={
                'verbose_name_plural': 'Присоединиться к проекту',
            },
        ),
        migrations.CreateModel(
            name='MediaKit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediakit', models.FileField(blank=True, null=True, upload_to='', verbose_name='mediakit')),
            ],
            options={
                'verbose_name_plural': 'Медиакит',
            },
        ),
        migrations.AlterField(
            model_name='tags',
            name='order',
            field=models.IntegerField(choices=[(0, 'Главное меню'), (1, 'под меню'), (2, 'тег')], default=1, verbose_name='Уровень меню'),
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': 'категории',
            },
        ),
    ]
