# Generated by Django 3.0.5 on 2020-05-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20200516_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagColorsEN',
            fields=[
                ('tagcolors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.TagColors')),
            ],
            options={
                'verbose_name': 'Tag color',
                'verbose_name_plural': 'Tag colors',
            },
            bases=('blog.tagcolors',),
        ),
        migrations.CreateModel(
            name='TagsEN',
            fields=[
                ('tags_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Tags')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
            bases=('blog.tags',),
        ),
        migrations.AddField(
            model_name='tags',
            name='locale',
            field=models.CharField(choices=[('ru', 'ru'), ('en', 'en')], default='ru', max_length=250, verbose_name='Language'),
        ),
        migrations.DeleteModel(
            name='BlogPageTag',
        ),
    ]
