# Generated by Django 3.0.5 on 2020-05-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_auto_20200516_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='parent_id',
            field=models.ForeignKey(blank=True, limit_choices_to={models.CharField(choices=[('ru', 'ru'), ('en', 'en')], default='ru', max_length=250, verbose_name='Language'): 'ru'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Tags', verbose_name='Родительский TAG'),
        ),
    ]
