# Generated by Django 3.0.5 on 2020-05-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_auto_20200516_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='order',
            new_name='level',
        ),
        migrations.AlterField(
            model_name='tagcolors',
            name='tag_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 0}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagcolors_tag', to='blog.Tags', verbose_name='Тег'),
        ),
    ]
