# Generated by Django 3.0.5 on 2020-05-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_auto_20200516_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='intro',
        ),
    ]
