# Generated by Django 3.0.5 on 2020-06-01 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_tagcolors_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='main_color',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(locale='ru'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.TagColors', verbose_name='Основной цвет'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='main_tag',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('level', 0), ('locale', 'ru')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.Tags', verbose_name='Основной тег'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='ontop',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='поднять'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='sub_tag',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('parent_id_id__isnull', False), ('locale', 'ru')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.Tags', verbose_name='Дополнительный тег'),
        ),
        migrations.AlterField(
            model_name='tagcolors',
            name='tag_id',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(level=0), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagcolors_tag', to='blog.Tags', verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='parent_id',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(parent_id_id__isnull=True), null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Tags', verbose_name='Родительский TAG'),
        ),
    ]
