# Generated by Django 3.0.5 on 2020-06-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_auto_20200602_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtoproject',
            name='subject',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
