# Generated by Django 3.0.5 on 2020-06-20 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0060_auto_20200609_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='main_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.TagColors', verbose_name='Основной цвет'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='main_tag',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(level=0), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.Tags', verbose_name='Основной тег'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='ontop',
            field=models.BooleanField(blank=True, default=False, verbose_name='поднять'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='sub_tag',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(parent_id_id__isnull=False), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.Tags', verbose_name='Дополнительный тег'),
        ),
    ]
