# Generated by Django 3.0.5 on 2020-05-02 14:09

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0060_blogpage_artical_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='artical_title',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True, verbose_name='Заголовок для статьи'),
        ),
    ]
