# Generated by Django 3.0.5 on 2020-07-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0061_auto_20200620_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typedpagegalleryimage',
            options={'ordering': ('sort_order',), 'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнера'},
        ),
        migrations.AddField(
            model_name='blogpage',
            name='title_colors',
            field=models.CharField(choices=[('white', 'Белый'), ('black', 'Черный')], default='black', max_length=10, verbose_name='Цвет заголовка внутри карточки'),
        ),
    ]
