# Generated by Django 3.0.5 on 2020-05-02 14:33

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0061_auto_20200502_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='artical_title',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.RawHTMLBlock()), ('ontop', wagtail.core.blocks.BooleanBlock())], blank=True, null=True, verbose_name='Заголовок для статьи'),
        ),
    ]
