# Generated by Django 3.0.5 on 2020-07-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0062_auto_20200709_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='title_colors',
            new_name='title_color',
        ),
    ]
