# Generated by Django 3.0.5 on 2020-05-02 14:44

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0062_auto_20200502_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='ontop',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='artical_title',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True, verbose_name='Заголовок для статьи'),
        ),
    ]
