# Generated by Django 3.0.5 on 2020-05-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0063_auto_20200502_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='a_test',
            field=models.URLField(null=True),
        ),
    ]
