# Generated by Django 3.0.5 on 2020-07-14 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0064_blogpage_title_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'ordering': ('page_ptr_id', '-date'), 'verbose_name': 'Статья'},
        ),
        migrations.AddField(
            model_name='blogpage',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 11, 24, 24, 155457), verbose_name='Время публикации'),
        ),
    ]
