# Generated by Django 3.0.5 on 2020-05-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0064_blogpage_a_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='a_test',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
