# Generated by Django 3.0.5 on 2020-05-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0065_auto_20200502_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='a_test',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
