# Generated by Django 3.0.5 on 2020-07-14 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0065_auto_20200714_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 9, 4, 56, 71439, tzinfo=utc), verbose_name='Время публикации'),
        ),
    ]
