# Generated by Django 3.0.5 on 2020-05-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0066_auto_20200502_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='a_test',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='artical_title',
            field=models.TextField(max_length=200, null=True, verbose_name='Заголовок для статьи'),
        ),
    ]
