# Generated by Django 3.0.5 on 2020-08-28 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0068_auto_20200720_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 10, 0, 4, 705354, tzinfo=utc), verbose_name='Время публикации'),
        ),
    ]
