# Generated by Django 3.0.5 on 2020-08-30 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0069_auto_20200828_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 12, 37, 16, 842705, tzinfo=utc), verbose_name='Время публикации'),
        ),
    ]
