# Generated by Django 3.0.5 on 2020-05-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0069_coloredtag_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='card_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок карточки'),
        ),
    ]
