# Generated by Django 3.0.5 on 2020-05-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0070_blogpage_card_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='card_title',
            field=models.CharField(blank=True, max_length=16, verbose_name='Заголовок карточки'),
        ),
    ]
