# Generated by Django 3.0.5 on 2020-05-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0071_auto_20200504_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloredtag',
            name='order_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
    ]
