# Generated by Django 3.0.5 on 2020-05-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0074_auto_20200505_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='artical_title',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Заголовок для статьи'),
        ),
    ]
