# Generated by Django 3.0.5 on 2020-05-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0075_auto_20200506_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='ontop',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
