# Generated by Django 3.0.5 on 2020-05-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0077_auto_20200506_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='card_sub_title',
            field=models.CharField(blank=True, max_length=16, verbose_name='Подголовок карточки'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(max_length=250, verbose_name='Тект ховера карточки'),
        ),
    ]
