# Generated by Django 3.0.5 on 2020-05-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0079_auto_20200508_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloredtag',
            name='order',
            field=models.CharField(blank=True, choices=[('main', 'Главное меню'), ('sub_main', 'под меню')], max_length=250, null=True, verbose_name='Уровень меню'),
        ),
    ]
