# Generated by Django 3.0.5 on 2020-05-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0081_auto_20200508_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloredtag',
            name='order',
            field=models.CharField(choices=[(0, 'Главное меню'), (1, 'под меню')], default=1, max_length=250, verbose_name='Уровень меню'),
        ),
    ]
