# Generated by Django 3.0.5 on 2020-05-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0082_auto_20200508_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloredtag',
            name='order',
            field=models.CharField(blank=True, choices=[(0, 'Главное меню'), (1, 'под меню')], default=1, max_length=250, null=True, verbose_name='Уровень меню'),
        ),
    ]
