# Generated by Django 3.0.5 on 2020-05-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0083_auto_20200508_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloredtag',
            name='order',
            field=models.CharField(blank=True, choices=[(0, 'Главное меню'), (1, 'под меню')], max_length=250, null=True, verbose_name='Уровень меню'),
        ),
    ]
