# Generated by Django 3.0.5 on 2020-05-08 09:36

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0086_auto_20200508_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcolors',
            name='tag_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagcolors_tag', to='blog.ColoredTag'),
        ),
        migrations.AlterField(
            model_name='tagcolors',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tagcolors',
            name='color_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название цвета'),
        ),
    ]
