# Generated by Django 3.0.5 on 2020-05-08 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0090_auto_20200508_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloredtag',
            name='tag',
            field=models.ForeignKey(blank=True, limit_choices_to={'order': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='blog.Tag'),
        ),
    ]
