# Generated by Django 3.0.5 on 2020-05-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0095_auto_20200508_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcolors',
            name='tag_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'order': 0}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagcolors_tag', to='blog.ColoredTag', verbose_name='Тег'),
        ),
    ]
