# Generated by Django 3.0.5 on 2020-05-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='text_color',
            field=models.CharField(choices=[('white', 'Белый'), ('black', 'Черный')], default='black', max_length=250, verbose_name='Цвет текста'),
        ),
    ]
