# Generated by Django 3.0.5 on 2020-05-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_photo_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='text_color',
            field=models.CharField(choices=[('white', 'Белый'), ('black', 'Черный')], default='white', max_length=250, verbose_name='Цвет текста'),
        ),
    ]
