# Generated by Django 3.0.5 on 2020-04-21 15:47

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_auto_20200421_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='gallery',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='slider.Gallery'),
        ),
    ]
