# Generated by Django 3.0.5 on 2020-05-16 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_auto_20200514_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoEN',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='slider.Photo')),
            ],
            bases=('slider.photo',),
        ),
        migrations.AddField(
            model_name='photo',
            name='locale',
            field=models.CharField(choices=[('ru', 'ru'), ('en', 'en')], default='ru', max_length=250, verbose_name='Language'),
        ),
    ]
