# Generated by Django 3.0.5 on 2020-06-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_auto_20200516_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-id'], 'verbose_name': 'Изображение слайдера', 'verbose_name_plural': 'Изображения слайдера'},
        ),
        migrations.AddField(
            model_name='photo',
            name='draft',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='черновик'),
        ),
        migrations.AddField(
            model_name='photo',
            name='ontop',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='в начало'),
        ),
        migrations.AddField(
            model_name='photo',
            name='order_num',
            field=models.IntegerField(blank=True, default=999, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='link',
            field=models.CharField(max_length=255, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, verbose_name='подзаголовок'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='заголовок'),
        ),
    ]
