# Generated by Django 3.0.5 on 2020-04-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_auto_20200421_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдер'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Изображения слайдера', 'verbose_name_plural': 'Изображения слайдера'},
        ),
    ]
