# Generated by Django 3.0.5 on 2020-04-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0005_auto_20200421_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Изображение слайдера', 'verbose_name_plural': 'Изображения слайдера'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='sort_order',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
