# Generated by Django 3.0.5 on 2020-06-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0005_auto_20200601_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-ontop', 'order_num', 'draft', '-id'], 'verbose_name': 'Изображение слайдера', 'verbose_name_plural': 'Изображения слайдера'},
        ),
    ]
